version: 2
updates:
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      android-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: nuget
    directory: /windows
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      nuget-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
